# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

# .github/workflows/master_logyxaccountingtest.yml
name: Build and deploy ASP.Net Core app to Azure Web App - LogyxAccountingTest

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  build:
    runs-on: ubuntu-latest  # faster; switch back to windows-latest if you need Windows-specific tooling
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x  # installs latest 8 SDK
      # If you use private NuGet feeds, uncomment and configure:
      # - name: Authenticate private NuGet feeds
      #   run: dotnet nuget add source "https://YOUR_FEED_URL" --name PrivateFeed --username USER --password "${{ secrets.NUGET_FEED_TOKEN }}" --store-password-in-clear-text

      - name: Restore
        run: dotnet restore ./LogyxAccounting.sln --nologo -v minimal

      - name: Build
        run: dotnet build ./LogyxAccounting.sln -c Release --no-restore -v minimal

      # If you have client assets (npm), add before publish:
      # - name: Build client assets
      #   run: |
      #     npm ci
      #     npm run build

      - name: Publish
        run: dotnet publish ./LogyxAccounting.csproj -c Release -o ${{ github.workspace }}/publish --no-build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: drop
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: drop
          path: ./drop

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: LogyxAccountingTest
          slot-name: Production
          package: ./drop
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F2D24315337E4A2C87D826867DC61066 }}
